#!/usr/bin/env python3
"""Generate original faceted-character GeckoLib geometry for Rift Companions.

This generator deliberately replaces the former flat/Steve-like silhouette with
an original, cube-only faceted character rig: a tapered head, independent eyes,
lids, brows, jaw, articulated limbs, layered hair, and ordinary late-1980s
clothing. It uses only GeckoLib-compatible cuboids and authored animation bones;
it does not import, convert, or depend on Yes Steve Model or any external model.

The canonical animation backbone remains stable so gameplay-facing animation
selection continues to work. Role-prefixed visual bones are presentation-only.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GEO = ROOT / "src/main/resources/assets/riftcompanions/geo"
GEO.mkdir(parents=True, exist_ok=True)
TEXTURE_SIZE = 512

# All new geometry maps against the procedural 512px atlas generated by
# generate_high_res_textures.py. The atlas is a technical UV sheet; it is not a
# visible square skin on the faceted model.
ATLAS: dict[str, tuple[int, int, int, int]] = {
    "head_front": (0, 0, 96, 96),
    "head_back": (96, 0, 96, 96),
    "head_left": (192, 0, 64, 96),
    "head_right": (256, 0, 64, 96),
    "head_top": (320, 0, 96, 64),
    "head_bottom": (416, 0, 96, 64),
    "skin_tile": (320, 64, 48, 32),
    "hair_tile": (368, 64, 48, 32),
    "eye_tile": (416, 64, 48, 32),
    "metal_tile": (464, 64, 48, 32),
    "torso_front": (0, 112, 96, 144),
    "torso_back": (96, 112, 96, 144),
    "torso_left": (192, 112, 64, 144),
    "torso_right": (256, 112, 64, 144),
    "torso_top": (320, 112, 96, 64),
    "torso_bottom": (416, 112, 96, 64),
    "jacket_tile": (320, 176, 48, 80),
    "shirt_tile": (368, 176, 48, 80),
    "pants_tile": (416, 176, 48, 80),
    "leather_tile": (464, 176, 48, 80),
    "arm_left_front": (0, 272, 48, 120),
    "arm_left_back": (48, 272, 48, 120),
    "arm_right_front": (96, 272, 48, 120),
    "arm_right_back": (144, 272, 48, 120),
    "sleeve_tile": (192, 272, 48, 48),
    "cuff_tile": (240, 272, 48, 48),
    "field_tile": (288, 272, 48, 48),
    "accent_tile": (336, 272, 48, 48),
    "thread_tile": (384, 272, 48, 48),
    "boot_tile": (432, 272, 48, 48),
    "pack_tile": (480, 272, 32, 48),
    "hand_left": (192, 336, 48, 56),
    "hand_right": (240, 336, 48, 56),
    "leg_left_front": (0, 400, 48, 112),
    "leg_left_back": (48, 400, 48, 112),
    "leg_right_front": (96, 400, 48, 112),
    "leg_right_back": (144, 400, 48, 112),
    "knee_tile": (192, 400, 48, 48),
    "sole_tile": (240, 400, 48, 48),
    "cloth_tile": (288, 400, 48, 48),
    "utility_tile": (336, 400, 48, 48),
    "signal_tile": (384, 400, 48, 48),
    "weather_tile": (432, 400, 48, 48),
    "spare_tile": (480, 400, 32, 48),
}


@dataclass(frozen=True)
class Build:
    role: str
    torso_width: float
    torso_depth: float
    shoulder_width: float
    arm_width: float
    leg_width: float
    head_width: float
    outer: str
    inner: str
    trouser: str


BUILDS = {
    "seer": Build("seer", 6.25, 3.25, 7.50, 2.65, 2.72, 6.05, "cloth_tile", "shirt_tile", "pants_tile"),
    "guardian": Build("guardian", 7.40, 3.90, 8.90, 3.35, 3.18, 6.80, "weather_tile", "shirt_tile", "pants_tile"),
    "gifted": Build("gifted", 6.05, 3.15, 7.20, 2.58, 2.64, 5.90, "field_tile", "shirt_tile", "pants_tile"),
    "scout": Build("scout", 6.15, 3.20, 7.35, 2.62, 2.68, 6.00, "jacket_tile", "shirt_tile", "pants_tile"),
}


def uv(panel: str) -> dict[str, list[int]]:
    x, y, width, height = ATLAS[panel]
    return {"uv": [x, y], "uv_size": [width, height]}


def faces(north: str, south: str | None = None, west: str | None = None,
          east: str | None = None, up: str | None = None, down: str | None = None) -> dict[str, Any]:
    south = south or north
    west = west or north
    east = east or west
    up = up or north
    down = down or up
    return {
        "north": uv(north), "south": uv(south), "west": uv(west),
        "east": uv(east), "up": uv(up), "down": uv(down),
    }


def material(panel: str) -> dict[str, Any]:
    return faces(panel)


def cube(origin: list[float], size: list[float], surface: dict[str, Any], *, inflate: float = 0.0) -> dict[str, Any]:
    payload: dict[str, Any] = {"origin": origin, "size": size, "uv": surface}
    if inflate:
        payload["inflate"] = inflate
    return payload


def bone(name: str, parent: str | None, pivot: list[float], cubes: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {"name": name, "pivot": pivot}
    if parent:
        payload["parent"] = parent
    if cubes:
        payload["cubes"] = cubes
    return payload


FACE = faces("head_front", "head_back", "head_left", "head_right", "head_top", "head_bottom")
SKIN = material("skin_tile")
HAIR = material("hair_tile")
EYE = material("eye_tile")
IRIS = material("accent_tile")
PUPIL = material("thread_tile")
LID = material("skin_tile")
MOUTH = material("thread_tile")
METAL = material("metal_tile")
LEATHER = material("leather_tile")
BOOT = material("boot_tile")
SOLE = material("sole_tile")


def anatomy(spec: Build) -> list[dict[str, Any]]:
    """Animation-safe base plus an original tapered, faceted face and body."""
    half_torso = spec.torso_width / 2
    half_head = spec.head_width / 2
    shoulder_half = spec.shoulder_width / 2
    half_arm = spec.arm_width / 2
    half_leg = spec.leg_width / 2
    # Keep canonical pivots stable for existing animation/VFX contracts; role shape
    # changes come from surrounding visual geometry rather than moving backbone joints.
    left_arm_x = 5.0
    right_arm_x = -5.0
    left_leg_x = 2.0
    right_leg_x = -2.0
    arm_depth = max(2.45, spec.arm_width)
    leg_depth = max(2.55, spec.leg_width)

    return [
        bone("root", None, [0, 0, 0]),
        bone("body", "root", [0, 12, 0]),
        bone("chest", "body", [0, 20, 0]),
        # Tapered ribcage and waist remove the old single 8×12 Steve torso box.
        bone("torso_ribcage", "chest", [0, 19.0, 0], [
            cube([-half_torso, 15.0, -spec.torso_depth / 2], [spec.torso_width, 8.0, spec.torso_depth], material(spec.inner), inflate=0.01),
        ]),
        bone("torso_waist", "chest", [0, 14.2, 0], [
            cube([-(half_torso - 0.55), 12.0, -(spec.torso_depth - 0.25) / 2], [spec.torso_width - 1.10, 3.5, spec.torso_depth - 0.25], material(spec.inner), inflate=0.01),
        ]),
        bone("neck", "chest", [0, 24, 0], [
            cube([-1.55, 22.65, -1.55], [3.10, 1.80, 3.10], SKIN, inflate=0.01),
        ]),
        bone("head", "chest", [0, 24, 0]),
        # Faceted head: narrow crown/chin and fuller cheeks form an oval/octagonal silhouette.
        bone("face_core", "head", [0, 28.0, 0], [
            cube([-half_head, 25.65, -half_head], [spec.head_width, 5.95, spec.head_width], FACE, inflate=0.01),
        ]),
        bone("face_forehead", "head", [0, 31.0, 0], [
            cube([-(half_head - 0.55), 30.75, -(half_head - 0.24)], [spec.head_width - 1.10, 1.35, spec.head_width - 0.48], SKIN, inflate=0.01),
        ]),
        bone("face_left_cheek", "head", [-half_head, 28.0, 0], [
            cube([-(half_head + 0.52), 26.35, -(half_head - 0.60)], [0.95, 3.85, spec.head_width - 1.20], SKIN, inflate=0.01),
        ]),
        bone("face_right_cheek", "head", [half_head, 28.0, 0], [
            cube([half_head - 0.43, 26.35, -(half_head - 0.60)], [0.95, 3.85, spec.head_width - 1.20], SKIN, inflate=0.01),
        ]),
        bone("face_left_ear", "head", [-(half_head + 0.45), 27.6, 0], [
            cube([-(half_head + 0.78), 27.10, -0.72], [0.48, 1.65, 1.44], SKIN, inflate=0.01),
        ]),
        bone("face_right_ear", "head", [half_head + 0.45, 27.6, 0], [
            cube([half_head + 0.30, 27.10, -0.72], [0.48, 1.65, 1.44], SKIN, inflate=0.01),
        ]),
        bone("jaw", "head", [0, 24, -4]),
        bone("face_chin", "jaw", [0, 25.3, 0], [
            cube([-(half_head - 0.88), 24.20, -(half_head - 0.30)], [spec.head_width - 1.76, 1.85, spec.head_width - 0.60], SKIN, inflate=0.01),
        ]),
        bone("nose_bridge", "head", [0, 27.9, -half_head], [
            cube([-0.43, 27.15, -(half_head + 0.34)], [0.86, 1.55, 0.55], SKIN, inflate=0.01),
        ]),
        bone("nose_tip", "head", [0, 27.0, -half_head], [
            cube([-0.68, 26.75, -(half_head + 0.55)], [1.36, 0.48, 0.70], SKIN, inflate=0.01),
        ]),
        # Independent face components support authored blink, gaze, and expression clips.
        bone("eye_left_white", "head", [-1.45, 28.35, -half_head], [
            cube([-2.25, 27.95, -(half_head + 0.38)], [1.60, 0.82, 0.28], EYE, inflate=0.005),
        ]),
        bone("eye_right_white", "head", [1.45, 28.35, -half_head], [
            cube([0.65, 27.95, -(half_head + 0.38)], [1.60, 0.82, 0.28], EYE, inflate=0.005),
        ]),
        bone("eye_left_pupil", "head", [-1.45, 28.34, -half_head], [
            cube([-1.72, 28.10, -(half_head + 0.61)], [0.54, 0.48, 0.17], IRIS, inflate=0.005),
        ]),
        bone("eye_right_pupil", "head", [1.45, 28.34, -half_head], [
            cube([1.18, 28.10, -(half_head + 0.61)], [0.54, 0.48, 0.17], IRIS, inflate=0.005),
        ]),
        bone("eye_left_glint", "eye_left_pupil", [-1.45, 28.34, -half_head], [
            cube([-1.58, 28.35, -(half_head + 0.76)], [0.18, 0.16, 0.10], EYE, inflate=0.003),
        ]),
        bone("eye_right_glint", "eye_right_pupil", [1.45, 28.34, -half_head], [
            cube([1.32, 28.35, -(half_head + 0.76)], [0.18, 0.16, 0.10], EYE, inflate=0.003),
        ]),
        bone("eye_left_upper_lid", "head", [-1.45, 28.82, -half_head], [
            cube([-2.32, 28.68, -(half_head + 0.67)], [1.74, 0.24, 0.18], LID, inflate=0.004),
        ]),
        bone("eye_right_upper_lid", "head", [1.45, 28.82, -half_head], [
            cube([0.58, 28.68, -(half_head + 0.67)], [1.74, 0.24, 0.18], LID, inflate=0.004),
        ]),
        bone("eye_left_lower_lid", "head", [-1.45, 27.85, -half_head], [
            cube([-2.28, 27.74, -(half_head + 0.67)], [1.66, 0.18, 0.17], LID, inflate=0.004),
        ]),
        bone("eye_right_lower_lid", "head", [1.45, 27.85, -half_head], [
            cube([0.62, 27.74, -(half_head + 0.67)], [1.66, 0.18, 0.17], LID, inflate=0.004),
        ]),
        bone("brow_left", "head", [-1.45, 29.40, -half_head], [
            cube([-2.30, 29.27, -(half_head + 0.66)], [1.72, 0.27, 0.18], HAIR, inflate=0.004),
        ]),
        bone("brow_right", "head", [1.45, 29.40, -half_head], [
            cube([0.58, 29.27, -(half_head + 0.66)], [1.72, 0.27, 0.18], HAIR, inflate=0.004),
        ]),
        bone("mouth_neutral", "jaw", [0, 25.75, -half_head], [
            cube([-1.18, 25.52, -(half_head + 0.57)], [2.36, 0.23, 0.16], MOUTH, inflate=0.003),
        ]),
        # Animation bridge bones retained with segmented anatomy rather than one block limb.
        bone("left_arm", "chest", [left_arm_x, 22, 0]),
        bone("left_arm_upper", "left_arm", [left_arm_x, 22, 0], [
            cube([left_arm_x - half_arm, 16.55, -arm_depth / 2], [spec.arm_width, 5.45, arm_depth], material(spec.inner), inflate=0.01),
        ]),
        bone("left_arm_lower", "left_arm_upper", [left_arm_x, 16.55, 0], [
            cube([left_arm_x - half_arm + 0.10, 11.20, -(arm_depth - 0.10) / 2], [spec.arm_width - 0.20, 5.35, arm_depth - 0.10], material(spec.inner), inflate=0.01),
        ]),
        bone("left_hand", "left_arm_lower", [left_arm_x, 12, 0], [
            cube([left_arm_x - half_arm + 0.08, 9.15, -(arm_depth - 0.15) / 2], [spec.arm_width - 0.16, 2.05, arm_depth - 0.15], SKIN, inflate=0.01),
        ]),
        bone("right_arm", "chest", [right_arm_x, 22, 0]),
        bone("right_arm_upper", "right_arm", [right_arm_x, 22, 0], [
            cube([right_arm_x - half_arm, 16.55, -arm_depth / 2], [spec.arm_width, 5.45, arm_depth], material(spec.inner), inflate=0.01),
        ]),
        bone("right_arm_lower", "right_arm_upper", [right_arm_x, 16.55, 0], [
            cube([right_arm_x - half_arm + 0.10, 11.20, -(arm_depth - 0.10) / 2], [spec.arm_width - 0.20, 5.35, arm_depth - 0.10], material(spec.inner), inflate=0.01),
        ]),
        bone("right_hand", "right_arm_lower", [right_arm_x, 12, 0], [
            cube([right_arm_x - half_arm + 0.08, 9.15, -(arm_depth - 0.15) / 2], [spec.arm_width - 0.16, 2.05, arm_depth - 0.15], SKIN, inflate=0.01),
        ]),
        bone("left_leg", "root", [left_leg_x, 12, 0]),
        bone("left_leg_upper", "left_leg", [left_leg_x, 12, 0], [
            cube([left_leg_x - half_leg, 6.15, -leg_depth / 2], [spec.leg_width, 5.85, leg_depth], material(spec.trouser), inflate=0.01),
        ]),
        bone("left_leg_lower", "left_leg_upper", [left_leg_x, 6.15, 0], [
            cube([left_leg_x - half_leg + 0.10, 1.20, -(leg_depth - 0.12) / 2], [spec.leg_width - 0.20, 4.95, leg_depth - 0.12], material(spec.trouser), inflate=0.01),
        ]),
        bone("left_foot", "left_leg_lower", [left_leg_x, 0, -0.5], [
            cube([left_leg_x - half_leg, 0, -2.75], [spec.leg_width, 2.12, 4.65], BOOT, inflate=0.01),
        ]),
        bone("right_leg", "root", [right_leg_x, 12, 0]),
        bone("right_leg_upper", "right_leg", [right_leg_x, 12, 0], [
            cube([right_leg_x - half_leg, 6.15, -leg_depth / 2], [spec.leg_width, 5.85, leg_depth], material(spec.trouser), inflate=0.01),
        ]),
        bone("right_leg_lower", "right_leg_upper", [right_leg_x, 6.15, 0], [
            cube([right_leg_x - half_leg + 0.10, 1.20, -(leg_depth - 0.12) / 2], [spec.leg_width - 0.20, 4.95, leg_depth - 0.12], material(spec.trouser), inflate=0.01),
        ]),
        bone("right_foot", "right_leg_lower", [right_leg_x, 0, -0.5], [
            cube([right_leg_x - half_leg, 0, -2.75], [spec.leg_width, 2.12, 4.65], BOOT, inflate=0.01),
        ]),
        bone("accessory_1", "head", [0, 24, 0]),
        bone("accessory_2", "chest", [0, 20, 0]),
    ]


def sleeve_layers(spec: Build) -> list[dict[str, Any]]:
    half_arm = spec.arm_width / 2
    arm_x = 5.0
    arm_depth = max(2.45, spec.arm_width)
    return [
        bone(f"{spec.role}_left_upper_sleeve", "left_arm_upper", [arm_x, 19.2, 0], [
            cube([arm_x - half_arm - 0.12, 16.40, -arm_depth / 2 - 0.12], [spec.arm_width + 0.24, 5.52, arm_depth + 0.24], material(spec.outer), inflate=0.008),
        ]),
        bone(f"{spec.role}_right_upper_sleeve", "right_arm_upper", [-arm_x, 19.2, 0], [
            cube([-arm_x - half_arm - 0.12, 16.40, -arm_depth / 2 - 0.12], [spec.arm_width + 0.24, 5.52, arm_depth + 0.24], material(spec.outer), inflate=0.008),
        ]),
        bone(f"{spec.role}_left_lower_sleeve", "left_arm_lower", [arm_x, 13.8, 0], [
            cube([arm_x - half_arm, 11.05, -arm_depth / 2], [spec.arm_width, 5.42, arm_depth], material(spec.outer), inflate=0.008),
        ]),
        bone(f"{spec.role}_right_lower_sleeve", "right_arm_lower", [-arm_x, 13.8, 0], [
            cube([-arm_x - half_arm, 11.05, -arm_depth / 2], [spec.arm_width, 5.42, arm_depth], material(spec.outer), inflate=0.008),
        ]),
        bone(f"{spec.role}_left_cuff", "left_arm_lower", [arm_x, 11.8, 0], [
            cube([arm_x - half_arm - 0.08, 10.95, -arm_depth / 2 - 0.08], [spec.arm_width + 0.16, 1.15, arm_depth + 0.16], material("cuff_tile"), inflate=0.006),
        ]),
        bone(f"{spec.role}_right_cuff", "right_arm_lower", [-arm_x, 11.8, 0], [
            cube([-arm_x - half_arm - 0.08, 10.95, -arm_depth / 2 - 0.08], [spec.arm_width + 0.16, 1.15, arm_depth + 0.16], material("cuff_tile"), inflate=0.006),
        ]),
    ]


def seer_visuals(spec: Build) -> list[dict[str, Any]]:
    return [
        # Natural layered dark hair, with independent strands for authored sway.
        bone("seer_hair_crown", "accessory_1", [0, 30.8, 0], [cube([-2.85, 30.0, -2.95], [5.70, 2.15, 5.90], HAIR, inflate=0.015)]),
        bone("seer_hair_back", "accessory_1", [0, 27.8, 3.0], [cube([-3.15, 24.7, 2.75], [6.30, 6.25, 1.10], HAIR, inflate=0.012)]),
        bone("seer_hair_left_01", "accessory_1", [-2.7, 29.0, -3.1], [cube([-3.50, 27.2, -3.85], [1.28, 3.85, 0.62], HAIR, inflate=0.008)]),
        bone("seer_hair_left_02", "seer_hair_left_01", [-3.0, 26.7, -3.1], [cube([-3.65, 24.7, -3.75], [1.05, 2.70, 0.55], HAIR, inflate=0.008)]),
        bone("seer_hair_center_01", "accessory_1", [-0.75, 29.0, -3.1], [cube([-1.55, 27.35, -3.92], [1.50, 3.45, 0.68], HAIR, inflate=0.008)]),
        bone("seer_hair_center_02", "accessory_1", [0.85, 29.0, -3.1], [cube([0.05, 27.35, -3.92], [1.50, 3.45, 0.68], HAIR, inflate=0.008)]),
        bone("seer_hair_right_01", "accessory_1", [2.7, 29.0, -3.1], [cube([2.22, 27.2, -3.85], [1.28, 3.85, 0.62], HAIR, inflate=0.008)]),
        bone("seer_hair_right_02", "seer_hair_right_01", [3.0, 26.7, -3.1], [cube([2.60, 24.7, -3.75], [1.05, 2.70, 0.55], HAIR, inflate=0.008)]),
        # Open overshirt and plain tee: grounded layers, not a hood or talisman.
        bone("seer_flannel_left", "accessory_2", [2.1, 18.0, -2.0], [cube([0.10, 13.35, -2.05], [3.15, 9.25, 0.38], material("cloth_tile"), inflate=0.01)]),
        bone("seer_flannel_right", "accessory_2", [-2.1, 18.0, -2.0], [cube([-3.25, 13.35, -2.05], [3.15, 9.25, 0.38], material("cloth_tile"), inflate=0.01)]),
        bone("seer_tshirt_front", "accessory_2", [0, 17.9, -2.15], [cube([-1.25, 14.10, -2.25], [2.50, 7.65, 0.28], material("shirt_tile"), inflate=0.006)]),
        bone("seer_collar_left", "accessory_2", [2.15, 21.25, -2.0], [cube([0.25, 19.45, -2.24], [2.70, 3.15, 0.40], material("cloth_tile"), inflate=0.008)]),
        bone("seer_collar_right", "accessory_2", [-2.15, 21.25, -2.0], [cube([-2.95, 19.45, -2.24], [2.70, 3.15, 0.40], material("cloth_tile"), inflate=0.008)]),
        bone("seer_shirt_tail", "accessory_2", [0, 13.25, 1.85], [cube([-3.0, 10.25, 1.55], [6.0, 3.80, 0.50], material("cloth_tile"), inflate=0.008)]),
        *sleeve_layers(spec),
    ]


def guardian_visuals(spec: Build) -> list[dict[str, Any]]:
    return [
        bone("guardian_hair_short", "accessory_1", [0, 30.7, 0], [cube([-3.20, 29.85, -3.15], [6.40, 2.05, 6.30], HAIR, inflate=0.012)]),
        bone("guardian_hair_back", "accessory_1", [0, 28.4, 3.1], [cube([-3.25, 27.0, 2.95], [6.50, 3.30, 0.85], HAIR, inflate=0.008)]),
        bone("guardian_sideburn_left", "accessory_1", [-3.10, 27.4, -2.8], [cube([-3.72, 25.6, -3.35], [0.75, 3.10, 0.55], HAIR, inflate=0.006)]),
        bone("guardian_sideburn_right", "accessory_1", [3.10, 27.4, -2.8], [cube([2.97, 25.6, -3.35], [0.75, 3.10, 0.55], HAIR, inflate=0.006)]),
        bone("guardian_beard", "jaw", [0, 25.6, -3.4], [cube([-2.55, 24.35, -3.72], [5.10, 2.30, 0.55], HAIR, inflate=0.007)]),
        bone("guardian_workcoat_front", "accessory_2", [0, 18.0, -2.25], [cube([-3.95, 13.05, -2.25], [7.90, 9.75, 0.42], material("weather_tile"), inflate=0.012)]),
        bone("guardian_workcoat_back", "accessory_2", [0, 18.0, 2.15], [cube([-3.95, 13.05, 1.85], [7.90, 9.75, 0.52], material("weather_tile"), inflate=0.012)]),
        bone("guardian_collar_left", "accessory_2", [2.70, 21.3, -2.20], [cube([0.25, 19.35, -2.52], [3.30, 3.55, 0.45], LEATHER, inflate=0.008)]),
        bone("guardian_collar_right", "accessory_2", [-2.70, 21.3, -2.20], [cube([-3.55, 19.35, -2.52], [3.30, 3.55, 0.45], LEATHER, inflate=0.008)]),
        bone("guardian_shirt_front", "accessory_2", [0, 18.0, -2.35], [cube([-1.45, 14.0, -2.62], [2.90, 8.10, 0.27], material("shirt_tile"), inflate=0.006)]),
        bone("guardian_belt", "accessory_2", [0, 13.5, 0], [cube([-3.85, 12.72, -2.15], [7.70, 1.20, 4.30], LEATHER, inflate=0.008)]),
        bone("guardian_buckle", "guardian_belt", [0, 13.45, -2.30], [cube([-0.78, 12.98, -2.55], [1.56, 0.88, 0.28], METAL, inflate=0.004)]),
        bone("guardian_watch", "left_arm_lower", [3.95, 12.0, -1.6], [cube([3.55, 11.45, -2.10], [1.32, 1.12, 0.36], METAL, inflate=0.005)]),
        bone("guardian_coat_tail", "accessory_2", [0, 13.1, 2.10], [cube([-3.65, 10.2, 1.72], [7.30, 3.90, 0.55], material("weather_tile"), inflate=0.008)]),
        *sleeve_layers(spec),
    ]


def gifted_visuals(spec: Build) -> list[dict[str, Any]]:
    return [
        bone("gifted_hair_crown", "accessory_1", [0, 30.5, 0], [cube([-2.80, 29.6, -2.90], [5.60, 2.20, 5.80], HAIR, inflate=0.012)]),
        bone("gifted_hair_back", "accessory_1", [0, 27.4, 3.0], [cube([-3.10, 23.6, 2.80], [6.20, 7.25, 1.05], HAIR, inflate=0.010)]),
        bone("gifted_hair_left_01", "accessory_1", [-2.85, 28.4, -3.0], [cube([-3.55, 25.5, -3.78], [1.28, 5.40, 0.65], HAIR, inflate=0.008)]),
        bone("gifted_hair_left_02", "gifted_hair_left_01", [-3.0, 25.0, -3.0], [cube([-3.68, 22.8, -3.68], [1.08, 3.00, 0.55], HAIR, inflate=0.008)]),
        bone("gifted_hair_center", "accessory_1", [0, 28.8, -3.0], [cube([-1.55, 26.7, -3.88], [3.10, 4.20, 0.70], HAIR, inflate=0.008)]),
        bone("gifted_hair_right_01", "accessory_1", [2.85, 28.4, -3.0], [cube([2.27, 25.5, -3.78], [1.28, 5.40, 0.65], HAIR, inflate=0.008)]),
        bone("gifted_hair_right_02", "gifted_hair_right_01", [3.0, 25.0, -3.0], [cube([2.60, 22.8, -3.68], [1.08, 3.00, 0.55], HAIR, inflate=0.008)]),
        bone("gifted_denim_front", "accessory_2", [0, 18.0, -2.10], [cube([-3.28, 13.2, -2.12], [6.56, 9.55, 0.38], material("field_tile"), inflate=0.010)]),
        bone("gifted_denim_back", "accessory_2", [0, 18.0, 2.05], [cube([-3.28, 13.2, 1.72], [6.56, 9.55, 0.46], material("field_tile"), inflate=0.010)]),
        bone("gifted_collar_left", "accessory_2", [2.15, 21.3, -2.10], [cube([0.22, 19.40, -2.42], [2.75, 3.35, 0.42], material("field_tile"), inflate=0.008)]),
        bone("gifted_collar_right", "accessory_2", [-2.15, 21.3, -2.10], [cube([-2.97, 19.40, -2.42], [2.75, 3.35, 0.42], material("field_tile"), inflate=0.008)]),
        bone("gifted_tshirt_front", "accessory_2", [0, 17.9, -2.25], [cube([-1.32, 14.05, -2.48], [2.64, 7.80, 0.24], material("shirt_tile"), inflate=0.006)]),
        bone("gifted_zipper", "accessory_2", [0, 17.9, -2.35], [cube([-0.13, 13.4, -2.62], [0.26, 9.18, 0.14], METAL, inflate=0.003)]),
        bone("gifted_front_pocket", "accessory_2", [2.05, 15.9, -2.15], [cube([0.72, 14.2, -2.38], [2.10, 2.35, 0.32], material("field_tile"), inflate=0.006)]),
        bone("gifted_watch", "right_arm_lower", [-3.95, 12.0, -1.6], [cube([-4.85, 11.45, -2.10], [1.32, 1.12, 0.36], METAL, inflate=0.005)]),
        bone("gifted_jacket_tail", "accessory_2", [0, 13.1, 2.0], [cube([-3.05, 10.25, 1.68], [6.10, 3.70, 0.50], material("field_tile"), inflate=0.008)]),
        *sleeve_layers(spec),
    ]


def scout_visuals(spec: Build) -> list[dict[str, Any]]:
    return [
        bone("scout_hair_crown", "accessory_1", [0, 30.55, 0], [cube([-2.88, 29.6, -2.95], [5.76, 2.20, 5.90], HAIR, inflate=0.012)]),
        bone("scout_hair_back", "accessory_1", [0, 27.3, 3.0], [cube([-3.15, 23.2, 2.78], [6.30, 7.75, 1.08], HAIR, inflate=0.010)]),
        bone("scout_hair_left_01", "accessory_1", [-2.9, 28.3, -3.0], [cube([-3.62, 25.3, -3.82], [1.30, 5.55, 0.65], HAIR, inflate=0.008)]),
        bone("scout_hair_left_02", "scout_hair_left_01", [-3.05, 24.8, -3.0], [cube([-3.75, 21.9, -3.70], [1.10, 3.55, 0.56], HAIR, inflate=0.008)]),
        bone("scout_hair_front_left", "accessory_1", [-1.1, 29.0, -3.0], [cube([-2.05, 26.9, -3.92], [1.75, 4.15, 0.70], HAIR, inflate=0.008)]),
        bone("scout_hair_front_right", "accessory_1", [1.15, 29.0, -3.0], [cube([0.30, 26.9, -3.92], [1.75, 4.15, 0.70], HAIR, inflate=0.008)]),
        bone("scout_hair_right_01", "accessory_1", [2.9, 28.3, -3.0], [cube([2.32, 25.3, -3.82], [1.30, 5.55, 0.65], HAIR, inflate=0.008)]),
        bone("scout_hair_right_02", "scout_hair_right_01", [3.05, 24.8, -3.0], [cube([2.65, 21.9, -3.70], [1.10, 3.55, 0.56], HAIR, inflate=0.008)]),
        bone("scout_jacket_front", "accessory_2", [0, 18.0, -2.12], [cube([-3.35, 13.2, -2.15], [6.70, 9.55, 0.38], material("jacket_tile"), inflate=0.010)]),
        bone("scout_jacket_back", "accessory_2", [0, 18.0, 2.05], [cube([-3.35, 13.2, 1.72], [6.70, 9.55, 0.46], material("jacket_tile"), inflate=0.010)]),
        bone("scout_collar_left", "accessory_2", [2.22, 21.3, -2.12], [cube([0.22, 19.40, -2.44], [2.82, 3.35, 0.42], material("jacket_tile"), inflate=0.008)]),
        bone("scout_collar_right", "accessory_2", [-2.22, 21.3, -2.12], [cube([-3.04, 19.40, -2.44], [2.82, 3.35, 0.42], material("jacket_tile"), inflate=0.008)]),
        bone("scout_tshirt_front", "accessory_2", [0, 17.9, -2.25], [cube([-1.38, 14.05, -2.48], [2.76, 7.80, 0.24], material("shirt_tile"), inflate=0.006)]),
        bone("scout_zipper", "accessory_2", [0, 17.9, -2.35], [cube([-0.13, 13.4, -2.62], [0.26, 9.18, 0.14], METAL, inflate=0.003)]),
        bone("scout_left_pocket", "accessory_2", [2.05, 15.9, -2.15], [cube([0.72, 14.2, -2.38], [2.10, 2.35, 0.32], material("jacket_tile"), inflate=0.006)]),
        bone("scout_right_pocket", "accessory_2", [-2.05, 15.9, -2.15], [cube([-2.82, 14.2, -2.38], [2.10, 2.35, 0.32], material("jacket_tile"), inflate=0.006)]),
        bone("scout_watch", "left_arm_lower", [3.95, 12.0, -1.6], [cube([3.55, 11.45, -2.10], [1.32, 1.12, 0.36], METAL, inflate=0.005)]),
        bone("scout_jacket_tail", "accessory_2", [0, 13.1, 2.0], [cube([-3.10, 10.25, 1.68], [6.20, 3.70, 0.50], material("jacket_tile"), inflate=0.008)]),
        *sleeve_layers(spec),
    ]


def visual_bones(spec: Build) -> list[dict[str, Any]]:
    if spec.role == "seer":
        return seer_visuals(spec)
    if spec.role == "guardian":
        return guardian_visuals(spec)
    if spec.role == "gifted":
        return gifted_visuals(spec)
    if spec.role == "scout":
        return scout_visuals(spec)
    raise ValueError(spec.role)


def model(role: str) -> dict[str, Any]:
    spec = BUILDS[role]
    bones = anatomy(spec) + visual_bones(spec)
    return {
        "format_version": "1.12.0",
        "minecraft:geometry": [{
            "description": {
                "identifier": f"geometry.riftcompanions.{role}",
                "texture_width": TEXTURE_SIZE,
                "texture_height": TEXTURE_SIZE,
                "visible_bounds_width": 4.45,
                "visible_bounds_height": 4.65,
                "visible_bounds_offset": [0, 1.70, 0],
                "riftcompanions_rig_contract": "shared_humanoid_v2",
                "riftcompanions_visual_contract": "faceted_character_512_v2",
            },
            "bones": bones,
        }],
    }


def main() -> None:
    for role in BUILDS:
        (GEO / f"{role}.geo.json").write_text(json.dumps(model(role), indent=2) + "\n", encoding="utf-8")
    print("Generated four original faceted-character Geo models with independent facial and hair bones.")


if __name__ == "__main__":
    main()
