#!/usr/bin/env python3
"""Generate original English dialogue barks for the Rift Companions datapack loader."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/main/resources/data/riftcompanions/companions_dialogue/core_en_us.json"

# (role, trigger, priority, cooldown_ticks, original English text)
LINES = [
# Guardian — practical protector
("guardian", "player_health_critical", 0, 1200, "That is enough. Your health is dropping. Stay behind me."),
("guardian", "player_health_critical", 0, 1200, "Take cover first. Winning is useless if we get trapped."),
("guardian", "player_health_critical", 0, 1200, "No heroics. We need distance now."),
("guardian", "retreat_start", 1, 900, "We have a reason to leave. Regroup and use the route back."),
("guardian", "retreat_start", 1, 900, "Simple plan: stay close and reach safe ground."),
("guardian", "retreat_start", 1, 900, "This is not a panic run. Move together."),
("guardian", "retreat_arrived", 2, 1000, "We made space. Check yourselves before we decide anything else."),
("guardian", "retreat_arrived", 2, 1000, "Good. Treat injuries before we talk about going back."),
("guardian", "retreat_arrived", 2, 1000, "The route held. Remember this place."),
("guardian", "unstuck", 1, 1600, "Back where you belong. We will not repeat that route blindly."),
("guardian", "unstuck", 1, 1600, "The path failed, not the team. We have a fallback now."),
("guardian", "unknown_threat", 2, 1300, "New threat. No guessing."),
("guardian", "unknown_threat", 2, 1300, "Watch it from a distance before anyone commits."),
("guardian", "unknown_threat", 2, 1300, "Nobody rushes in. Information first."),
("guardian", "night_risk", 2, 1800, "Night is close. Do we have a route home or a safe point?"),
("guardian", "night_risk", 2, 1800, "Before it gets dark, mark somewhere we can return to."),
("guardian", "structure_found", 2, 1800, "A single entrance is not a plan. Find an exit too."),
("guardian", "structure_found", 2, 1800, "We can mark it and return prepared. We do not have to enter now."),
("guardian", "creeper_near", 0, 1000, "Creeper near the protected area. Do not drive it toward the build."),
("guardian", "creeper_near", 0, 1000, "Move it into open ground. We need space, not an explosion."),
("guardian", "guard_order", 1, 1000, "I will hold the front. Keep the rear from opening up."),
("guardian", "guard_order", 1, 1000, "Stay where I can see you. Do not let them split us."),
("guardian", "post_crisis", 3, 2400, "Everyone is still standing. That matters."),
("guardian", "post_crisis", 3, 2400, "We can learn from that later. Not while everyone is still tense."),
("guardian", "resource_low", 2, 2000, "Healing is low. Do not stay in an unknown area too long."),
("guardian", "resource_low", 2, 2000, "Supplies first. Treasure can wait."),
("guardian", "base_return", 4, 4800, "Check the doors, then take a breath."),
("guardian", "base_return", 4, 4800, "This place stays safe because we take care of it."),
("guardian", "plan_cancelled", 2, 1200, "Plan cancelled. We go back to something simple and stay together."),
("guardian", "plan_cancelled", 2, 1200, "Your call. Safety is still the priority."),
("guardian", "regroup", 1, 1200, "Close the gap. Stay where I can see you."),
("guardian", "regroup", 1, 1200, "Formation first. Then we fight."),
("guardian", "player_support", 3, 3200, "You made the safe call. Keep doing that."),
# Seer — cautious observer
("seer", "anomaly_found", 1, 1700, "There is a strange signal. I cannot explain it yet, so do not rush in."),
("seer", "anomaly_found", 1, 1700, "Something here does not fit. We need a way back before we investigate."),
("seer", "anomaly_found", 1, 1700, "I can feel a pattern, but it is incomplete."),
("seer", "sense_clear", 2, 1800, "I do not see that kind of signal. That does not prove the place is safe."),
("seer", "sense_clear", 2, 1800, "Nothing linked is visible. We should still trust what we can actually see."),
("seer", "sense_direction", 1, 1400, "The signal is in that direction. Keep your distance from it."),
("seer", "sense_direction", 1, 1400, "The link is close, but not a reason to be reckless."),
("seer", "retreat_start", 1, 1200, "The signal is weaker behind us. This way is better."),
("seer", "retreat_start", 1, 1200, "Do not look back too long. Stay together."),
("seer", "retreat_arrived", 3, 2000, "It feels quieter here. I think we can think clearly now."),
("seer", "unstuck", 2, 2000, "I found the group again. The route was wrong, not you."),
("seer", "unknown_threat", 2, 1500, "Its movement is different. Let us watch before we get close."),
("seer", "unknown_threat", 2, 1500, "I do not know it. That is why we should not guess."),
("seer", "regroup", 1, 1200, "Do not let it separate us. Stay where we can see each other."),
("seer", "regroup", 1, 1200, "A little closer. It is easier to help when we remain a team."),
("seer", "night_risk", 3, 2400, "At night, sounds overlap. Do not mistake every sound for a warning, but do not ignore them."),
("seer", "structure_found", 2, 1800, "Something happened here. We do not have to understand all of it today."),
("seer", "structure_found", 2, 1800, "The quiet inside worries me more than the noise."),
("seer", "memory_revisit", 3, 4800, "We have been here before. I remember agreeing to be more careful."),
("seer", "memory_revisit", 3, 4800, "This place is a reminder that the way back matters."),
("seer", "team_rescue", 1, 1800, "The left side is calmer. If we move, we should move now."),
("seer", "team_rescue", 1, 1800, "The danger is behind you. There is a small opening ahead."),
("seer", "post_crisis", 4, 3600, "We do not have to talk about all of it right away."),
("seer", "post_crisis", 4, 3600, "Being quiet is not always a bad thing."),
("seer", "base_return", 4, 4800, "I like knowing where everyone is. This place helps."),
("seer", "base_return", 4, 4800, "We should write down what we learned before it becomes only a feeling."),
("seer", "resource_found", 2, 2400, "This is unfamiliar. Keep it safe instead of guessing what it does."),
("seer", "resource_found", 2, 2400, "We can mark it. We do not have to take everything to learn from it."),
("seer", "player_support", 3, 3200, "You listened to the warning at the right time. Thank you."),
("seer", "player_support", 3, 3200, "We are not alone here. That changes things."),
("seer", "hive_disrupt", 1, 1400, "The link weakened for a moment. Do not waste it."),
("seer", "hive_disrupt", 1, 1400, "I can slow it down, but I cannot hold it forever."),
("seer", "hive_disrupt", 1, 1400, "Do not rely on the link alone. Keep moving."),
("seer", "hive_strain", 2, 1800, "I cannot use the link again yet. I need time."),
# Gifted — rescue and power limits
("gifted", "power_low", 1, 1200, "I do not have enough strength for something big. We need to choose carefully."),
("gifted", "power_low", 1, 1200, "I can help, but not for long."),
("gifted", "shield_active", 1, 1000, "The shield is ready. Stay close."),
("gifted", "shield_active", 1, 1000, "You have a short opening. Use it."),
("gifted", "shield_end", 2, 1200, "The shield is gone. Do not depend on it now."),
("gifted", "push_success", 1, 1000, "I made space. Move."),
("gifted", "push_success", 1, 1000, "I pushed them back a little. It will not last."),
("gifted", "rescue_start", 0, 900, "I can reach you. Do not move."),
("gifted", "rescue_start", 0, 900, "Hold still. I will pull you to safety."),
("gifted", "rescue_success", 1, 1400, "You are safe now. Do not go back into the same danger."),
("gifted", "rescue_success", 1, 1400, "Done. We should move before they return."),
("gifted", "rescue_failed", 0, 1200, "I could not find a safe place to pull you. We need to reposition."),
("gifted", "rescue_failed", 0, 1200, "I will not move you into something worse. Make some space first."),
("gifted", "retreat_start", 1, 1200, "I can cover you for a moment. Go."),
("gifted", "retreat_start", 1, 1200, "If we move now, I can keep them back."),
("gifted", "unknown_threat", 2, 1800, "I can feel something, but I do not understand it yet."),
("gifted", "unknown_threat", 2, 1800, "I will not use power just to test it."),
("gifted", "structure_found", 3, 2400, "I can stay near the entrance. We do not all have to go inside."),
("gifted", "structure_found", 3, 2400, "If someone gets trapped, I will try to help. We still need a plan."),
("gifted", "post_crisis", 3, 3200, "I am tired, but I am here."),
("gifted", "post_crisis", 3, 3200, "We can rest for a moment, then decide."),
("gifted", "base_return", 4, 4800, "I like this place. We can rest here."),
("gifted", "base_return", 4, 4800, "Everyone came back. That matters."),
("gifted", "player_support", 3, 3200, "You asked before using power. That makes the plan safer."),
("gifted", "player_support", 3, 3200, "You protected people first. That was the right call."),
("gifted", "team_rescue", 1, 1500, "I can protect them if you make space."),
("gifted", "team_rescue", 1, 1500, "Do not crowd the rescue. I need a clear path."),
("gifted", "recovery", 3, 2800, "I need a minute. I am not finished; I just need to focus again."),
("gifted", "recovery", 3, 2800, "Do not rely on my power alone."),
("gifted", "night_risk", 4, 4200, "At night, I stay closer to the team."),
("gifted", "night_risk", 4, 4200, "If we stay together, I can protect you better."),
# Scout — routes, terrain and grounded support
("scout", "scout_start", 1, 1000, "I will check the route and return. Short range only."),
("scout", "scout_start", 1, 1000, "Quick scout, not a journey. I will stay in range."),
("scout", "scout_result", 1, 1400, "I found higher ground. The route is clearer from there."),
("scout", "scout_result", 1, 1400, "The path ahead is open, but do not walk the edge."),
("scout", "scout_result", 1, 1400, "I am back. There is a cleaner route on the other side."),
("scout", "scout_failed", 2, 1500, "That route is not reliable. I will not lead us into a dead end."),
("scout", "scout_failed", 2, 1500, "I do not have a safe path there. We should choose something smarter."),
("scout", "route_blocked", 1, 1200, "The route is blocked. We go around, not deeper into a trap."),
("scout", "route_blocked", 1, 1200, "That is not a shortcut. It is a slow trap. Turn here."),
("scout", "retreat_start", 1, 1000, "The route is open. Follow me and stay off the cliff edge."),
("scout", "retreat_start", 1, 1000, "Not toward the drop. This direction is better."),
("scout", "retreat_arrived", 2, 1800, "Good. We have room to move again."),
("scout", "retreat_arrived", 2, 1800, "The route worked. Mark it for next time."),
("scout", "unstuck", 2, 1800, "The space was tight, but I am back. We have another route now."),
("scout", "unknown_threat", 2, 1600, "New monster? Let us learn from far away, thanks."),
("scout", "unknown_threat", 2, 1600, "Do not stand close just to see what it does."),
("scout", "structure_found", 2, 1800, "There is a visible side entrance. I will check the outside only."),
("scout", "structure_found", 2, 1800, "Before we enter, we need to know how we leave."),
("scout", "regroup", 1, 1200, "Everyone in. Give each other room to move, not room to disappear."),
("scout", "regroup", 1, 1200, "Do not make it easy for them to pick one of us off."),
("scout", "team_rescue", 1, 1500, "I found room on the right. Bring them here."),
("scout", "team_rescue", 1, 1500, "Do not crowd the rescue. Give them space."),
("scout", "night_risk", 3, 2600, "In the dark, the fast route becomes a falling route. Watch your footing."),
("scout", "night_risk", 3, 2600, "I can still see the ridge. It is our guide if we need to leave."),
("scout", "base_return", 4, 4800, "The base is not bad. A better lookout would help."),
("scout", "base_return", 4, 4800, "The way back is easier now. That is real progress."),
("scout", "post_crisis", 3, 3000, "Nobody has to pretend that was normal."),
("scout", "post_crisis", 3, 3000, "Let us sit down before somebody decides to be dramatic."),
("scout", "resource_found", 2, 2200, "Useful? Sure. Worth a cliff dive? No."),
("scout", "resource_found", 2, 2200, "Mark it. We can take it when the route is less terrible."),
("scout", "player_support", 3, 3200, "You chose the safe route. Strange, but a good decision."),
("scout", "player_support", 3, 3200, "You kept the team close. That makes my job easier."),
("scout", "grounding_success", 1, 1400, "Focus on me. You are here, and the route ahead is clear."),
("scout", "grounding_success", 1, 1400, "There. You are back with us. Move carefully."),
("scout", "focus_low", 2, 1800, "My head is not clear enough to guide us right now. Give me a minute."),
("scout", "focus_low", 2, 1800, "I will not call a route safe when I am not focused."),
]

# Coverage expansion: each role reaches the 70-line 1.0 content floor with
# useful P0/P1/P2/P3 families rather than ambient filler.
EXTRA_LINES = {
    "guardian": [
        ("weather", 3, "Rain cuts visibility. Stay closer."),
        ("weather", 3, "The storm is getting worse. Keep off open ground."),
        ("weather", 3, "Weather changed. Our route may need to change too."),
        ("dawn_check", 3, "New day. Check health, exits, and the route before we leave."),
        ("dawn_check", 3, "No briefing unless we need one. Just make sure everyone is ready."),
        ("base_prepare", 2, "Before the next trip, pick a goal we can finish safely."),
        ("base_prepare", 2, "Food, healing, and a way back. That is enough preparation."),
        ("plan_accepted", 1, "Plan accepted. Hold your positions and keep it simple."),
        ("plan_accepted", 1, "Good. We have a plan. Do not improvise unless the danger changes."),
        ("boss_phase", 1, "Something changed. Reset positions."),
        ("boss_phase", 1, "New phase. Do not trust the old plan blindly."),
        ("downed_danger", 0, "One of us is down. Clear space before you try the rescue."),
        ("downed_danger", 0, "Do not turn a rescue into two casualties. Hold the line."),
        ("safe_route", 2, "That route is worth remembering. A way back is a real resource."),
        ("safe_route", 2, "You marked the safe path. Good habit."),
        ("base_intention", 4, "A guard post here would make this place easier to defend."),
        ("base_intention", 4, "This entrance needs a clear lane. Keep it open."),
        ("village_protection", 2, "Villagers are not cover. Keep the fight away from them."),
        ("village_protection", 2, "Protect the people first. Loot can wait."),
        ("focus_target", 1, "That target is the problem. Keep the rest from closing in."),
        ("focus_target", 1, "Focus the threat that can hurt the team right now."),
        ("power_policy", 2, "Use power when it solves a real problem, not because it looks impressive."),
        ("power_policy", 2, "We do not build a plan around one person saving us."),
        ("memory_callback", 3, "We handled something like this before. Use what we learned."),
        ("memory_callback", 3, "The last time we ignored the route, it cost us time. Not again."),
        ("calm_base", 4, "Quiet is useful. Let it stay quiet for a minute."),
        ("calm_base", 4, "No emergency. That is a good place to start."),
        ("structure_exit", 2, "Before we go farther in, make sure we can come back out."),
        ("structure_exit", 2, "Mark the entrance. We do not leave people guessing where the exit is."),
        ("plan_failed", 2, "The plan failed. The team did not. We adjust."),
        ("plan_failed", 2, "We learned what does not work. That is still useful."),
        ("companion_return", 3, "Everyone is accounted for. Take a breath."),
        ("companion_return", 3, "The team is back together. That is the first win."),
        ("home_milestone", 4, "This place has held up for a while. Keep it that way."),
        ("home_milestone", 4, "A home is a route, a door, and people who return to it."),
        ("minimal_reply", 1, "I am here. Keep moving."),
        ("minimal_reply", 1, "Status is stable. Stay sharp."),
        ("resource_request", 2, "If you want me to carry an emergency item, hand it over. I will not take it."),
        ("resource_request", 2, "Keep the rare stuff with you. I only need what helps the team survive."),
    ],
    "seer": [
        ("weather", 3, "Rain makes every sound harder to separate."),
        ("weather", 3, "The storm is loud. Do not confuse it with the signal."),
        ("dawn_check", 3, "The morning is quiet. That gives us time to notice what changed."),
        ("dawn_check", 3, "Before we leave, I want to remember where the safe route starts."),
        ("base_prepare", 3, "If we investigate, I would rather have a way back first."),
        ("base_prepare", 3, "We can follow the clue later. It does not have to be today."),
        ("plan_accepted", 2, "Okay. I will watch for anything that does not fit the pattern."),
        ("plan_accepted", 2, "I will stay close and tell you what I actually notice."),
        ("boss_phase", 1, "The pattern changed. Do not stand where it expects you."),
        ("boss_phase", 1, "It is reacting differently now. We need a new opening."),
        ("downed_danger", 0, "There is an opening near the left side. It may not last."),
        ("downed_danger", 0, "The threat is shifting away for a second. Use that."),
        ("safe_route", 2, "That route feels familiar now. Familiar is useful when things go wrong."),
        ("safe_route", 2, "A marked path is more than a line. It is a promise that we can return."),
        ("base_intention", 4, "A journal point here would help us keep the important parts."),
        ("base_intention", 4, "This is a good place to stop and listen for a while."),
        ("village_protection", 3, "People should not have to become part of a fight they did not choose."),
        ("focus_target", 2, "That one is different from the others. Watch its movement."),
        ("focus_target", 2, "I can feel the link around that target. Be careful."),
        ("power_policy", 2, "The link is useful, but it is not a shortcut through every danger."),
        ("power_policy", 2, "If I use the link, make sure we know what we will do with the opening."),
        ("memory_callback", 3, "We have seen this kind of warning before. I do not want to ignore it twice."),
        ("memory_callback", 3, "Something about this place matches an old memory, but I need more evidence."),
        ("calm_base", 4, "It is easier to breathe when everyone is close by."),
        ("calm_base", 4, "The quiet here feels earned."),
        ("structure_exit", 2, "If we enter, stay where we can see each other."),
        ("structure_exit", 2, "The entrance is a memory too. Do not lose it."),
        ("plan_failed", 2, "We did not know enough. Next time, we will."),
        ("plan_failed", 2, "I should have said what I noticed sooner. I will next time."),
        ("companion_return", 3, "I am glad everyone came back."),
        ("companion_return", 3, "Being together changes what we can survive."),
        ("home_milestone", 4, "This place is becoming part of our story."),
        ("home_milestone", 4, "We have returned here enough that it feels like more than shelter."),
        ("minimal_reply", 1, "I am watching."),
        ("minimal_reply", 1, "I am with the team."),
        ("resource_request", 2, "If it is unfamiliar, let us record it before anyone uses it."),
        ("resource_request", 2, "We can come back for it if the route stays safe."),
    ],
    "gifted": [
        ("weather", 3, "The rain makes it harder to see far ahead."),
        ("weather", 3, "The thunder is loud. Stay close."),
        ("dawn_check", 3, "I feel better after resting. Are we ready?"),
        ("dawn_check", 3, "The day is starting. I want everyone to be safe."),
        ("base_prepare", 3, "Before we go, decide when you want me to use power."),
        ("base_prepare", 3, "I can help, but I do not want to be the whole plan."),
        ("plan_accepted", 2, "Okay. I will keep power for the moment it matters."),
        ("plan_accepted", 2, "I understand the plan. I will protect the opening."),
        ("boss_phase", 1, "My power will not hold it for long."),
        ("boss_phase", 1, "It is resisting. We need a safer opening."),
        ("downed_danger", 0, "I can shield the rescue, but clear the space first."),
        ("downed_danger", 0, "I can pull them only if there is somewhere safe to go."),
        ("safe_route", 2, "A safe route means I do not have to use power to fix every mistake."),
        ("safe_route", 2, "Thank you for marking the way back."),
        ("base_intention", 4, "A quiet place here would help me recover."),
        ("base_intention", 4, "I like having a place where nobody needs me to fight."),
        ("village_protection", 2, "Keep people out of the line of fire."),
        ("village_protection", 2, "I will not use a push near them unless there is no other choice."),
        ("focus_target", 1, "I can keep that target back for a moment."),
        ("focus_target", 1, "I see the target. Tell me when you need the opening."),
        ("power_policy", 2, "It helps when you ask instead of assuming."),
        ("power_policy", 2, "Power is safer when the team knows the limit."),
        ("memory_callback", 3, "We got through something like this before."),
        ("memory_callback", 3, "I remember how tired I was last time. I will save strength now."),
        ("calm_base", 4, "It is nice when nothing needs fixing."),
        ("calm_base", 4, "I can rest here."),
        ("structure_exit", 2, "I will stay near the exit until we know more."),
        ("structure_exit", 2, "Do not let the entrance disappear behind us."),
        ("plan_failed", 2, "That did not work. We can try again when we are ready."),
        ("plan_failed", 2, "We do not have to force it."),
        ("companion_return", 3, "Everyone is here. Good."),
        ("companion_return", 3, "We came back together."),
        ("home_milestone", 4, "This place feels safer every time we return."),
        ("home_milestone", 4, "Home means we have somewhere to recover."),
        ("minimal_reply", 1, "I am ready."),
        ("minimal_reply", 1, "Stay close."),
        ("resource_request", 2, "Give healing to whoever needs it most."),
        ("resource_request", 2, "I do not need rare items to recover. I need time."),
        ("quiet_recovery", 3, "I am recovering. Let the team handle the next few seconds without another power."),
    ],
    "scout": [
        ("weather", 3, "Rain ruins the long view. We should tighten the route."),
        ("weather", 3, "Storm ground is bad ground for a shortcut."),
        ("dawn_check", 3, "Daylight is good. Let us use it before we make another cave decision."),
        ("dawn_check", 3, "I can check the ridge after everyone is ready."),
        ("base_prepare", 3, "Give me a direction and a limit. I will bring back one useful answer."),
        ("base_prepare", 3, "A scout needs a route back, not just somewhere interesting to run."),
        ("plan_accepted", 2, "Got it. I will watch the edges and call the turns."),
        ("plan_accepted", 2, "Plan is clear. I will not wander off-script."),
        ("boss_phase", 1, "New pattern. Watch the ground before it hits again."),
        ("boss_phase", 1, "That was the warning. Move before the next one."),
        ("downed_danger", 0, "There is room on the right. Bring them through there."),
        ("downed_danger", 0, "Do not crowd the rescue. I will keep the path visible."),
        ("safe_route", 2, "Nice route. We can actually use that under pressure."),
        ("safe_route", 2, "Marked and remembered. That is how shortcuts stop being stupid."),
        ("base_intention", 4, "A lookout here would make the next route easier to read."),
        ("base_intention", 4, "Give me a clear line to the horizon and I can do more."),
        ("village_protection", 2, "Keep the fight outside the houses. The lanes are too tight."),
        ("village_protection", 2, "Do not make villagers part of the route problem."),
        ("focus_target", 1, "I have the target. Watch for the others trying to flank."),
        ("focus_target", 1, "That one is the priority. The route around it is still open."),
        ("power_policy", 2, "If we use a power, use it to make a route, not a fireworks show."),
        ("power_policy", 2, "A good opening is one we can actually move through."),
        ("memory_callback", 3, "We used this path before. It was safer than it looked."),
        ("memory_callback", 3, "I remember where that route stopped being safe."),
        ("calm_base", 4, "No monsters, no cliffs, no terrible shortcuts. Nice."),
        ("calm_base", 4, "The lookout is quiet. I can work with quiet."),
        ("structure_exit", 2, "I see one way in and one way out. That is enough to start carefully."),
        ("structure_exit", 2, "If the route closes, we leave. Simple."),
        ("plan_failed", 2, "The route did not hold. We find another one."),
        ("plan_failed", 2, "That was a bad call. I have a better angle next time."),
        ("companion_return", 3, "Everybody made it back. Good."),
        ("companion_return", 3, "No one got lost. I will take that win."),
        ("home_milestone", 4, "The way home is starting to feel automatic. Keep the markers anyway."),
        ("home_milestone", 4, "A base with a route is better than a base with a nice roof."),
        ("minimal_reply", 1, "Route is clear."),
        ("minimal_reply", 1, "I am on the edge."),
        ("resource_request", 2, "If you want ranged support later, keep some arrows set aside."),
        ("resource_request", 2, "One item is not worth walking into lava for. Mark it and move on."),
    ],
}

for role, entries_for_role in EXTRA_LINES.items():
    for trigger, priority, text in entries_for_role:
        LINES.append((role, trigger, priority, 2400 if priority >= 3 else 1400, text))

entries = [
    {
        "id": f"{role}.{trigger}.{index:03d}",
        "role": role,
        "trigger": trigger,
        "priority": priority,
        "cooldown_ticks": cooldown,
        "text": text,
    }
    for index, (role, trigger, priority, cooldown, text) in enumerate(LINES, 1)
]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps({"schema": 1, "locale": "en_us", "entries": entries}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(entries)} English dialogue entries to {OUT}")
