package com.riftcompanions.arc;

/** Observable gameplay facts, not kill counts or real-world deadlines. */
public enum ArcMilestone {
    RETREAT_SUCCEEDED,
    SAFE_ROUTE_MARKED,
    TEAM_SAFE_RETURN,
    PLAN_DECLINED_SAFELY,
    ANOMALY_DOCUMENTED,
    EVIDENCE_COMPARED,
    CAUTIOUS_OBSERVATION,
    WARNING_SUPPORTED_DECISION,
    RESCUE_SUCCEEDED,
    POWER_POLICY_RESPECTED,
    SHIELD_SAFE_EXIT,
    NONPOWER_PLAN_SUCCEEDED,
    SCOUT_SUCCEEDED,
    ROUTE_ANNOTATION_HELPED,
    SAFER_ROUTE_CHOSEN,
    ROUTE_PAIR_PLAN_SUCCEEDED
}
